# File tree navigation
alias b="cd .."
alias bb="cd ../.."
alias bbb="cd ../../.."
alias dev="cd ~/Development"

# git
alias gb="git branch"
alias gs="git status"
alias gpom="git pull origin master"
alias gpoom="git push origin master"

# gnome-settings
alias unblink="gsettings set org.gnome.desktop.interface cursor-blink false"
