filetype indent plugin on

imap <C-a> <Home>
imap <C-e> <End>

match Error /\s\+$/

nmap <Enter> o<Esc>k

noremap - <C-z>

set expandtab
set hlsearch
set incsearch
set nobackup
set nowritebackup
set shiftwidth=4
set smartcase
set softtabstop=4
set tabstop=4

syntax on
